### ISSUE TITLE
Readme instructions

### ISSUE THREAD

**Issue by haringsrob** [serganch/intellij-lsp#23]
Hi!

I know this project may be still in early stages. But if possible I would love to give it a try as it is something I have been looking for for a long time (with neovim instead of vscode).

I can make the lspconfig for neovim, and even tinker/try some java changes, but I personally mainly use phpstorm.

If you could give me some pointes to get started it would be appreciated.

Kind regards,

**Comment by serganch** [comment]
Hi, Rob! (sorry if I misinterpreted your name)

You're right, this is not only in early stages, but also very much experimental, and we're still not sure if we will able to prove its feasibility. Basically what we trying to achieve is to turn IntelliJ into an LSP server with as little language dependent parts as possible. Needless to say IntelliJ wasn't designed to be a backend of any kind so 99% of our work is fighting its intrinsic desktop UI nature with more or less success. And the future of this work isn't yet clear.
This project was heavily inspired by https://github.com/Ruin0x11/intellij-lsp-server. But we wanted to move beyond the limits of few particular languages.
If you want to try it, you should first configure an IDEA project around your sources, quit IDEA, then run `gradle runIde` in the root of `intellij-lsp`. It will launch an LSP server on localhost:8989. Currently this is the only way to communicate with the client. And no warranties, you know it :))

Good luck!

--
Sergey

**Comment by haringsrob** [comment]
Thanks for the writeup and I also notice the readme has been updated.

I did notice the requirements for `Java, Kotlin and Python IDEA plugins are required to be installed.` which won't work as they are not available for phpstorm.

But in any case, I will keep an eye on the project!

**Comment by serganch** [comment]
> I did notice the requirements for `Java, Kotlin and Python IDEA plugins are required to be installed.` which won't work as they are not available for phpstorm.
> 
This is a temporary constraint. We'll get rid of it soon

**Comment by haringsrob** [comment]
@serganch great, I will happily help test and maybe even fix issues when I get to run it on phpstorm.

This would be my dream setup I believe.

**Comment by serganch** [comment]
@haringsrob in my last commit I've made all the language dependencies optional. Not sure it works 100%, but you may try it with PhpStorm. If you decide to try please let me know if goes well

**Comment by haringsrob** [comment]
Hey @serganch

Gave it a try immediately, unfortunately it fails to activate with:

```
[Error - 18:57:28] Server initialization failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: org/eclipse/lsp4j/CompletionItemOptions
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NoClassDefFoundError: org/eclipse/lsp4j/CompletionItemOptions
	at org.rri.server.LspServer.defaultCompletionOptions(LspServer.java:88)
	at org.rri.server.LspServer.lambda$defaultServerCapabilities$5(LspServer.java:105)
	at org.rri.server.util.MiscUtil.with(MiscUtil.java:38)
	at org.rri.server.LspServer.defaultServerCapabilities(LspServer.java:97)
	at org.rri.server.LspServer.lambda$initialize$2(LspServer.java:80)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
Caused by: java.lang.ClassNotFoundException: org.eclipse.lsp4j.CompletionItemOptions PluginClassLoader(plugin=PluginDescriptor(name=Server, id=org.rri.server, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/PhpStorm/ch-0/222.3739.61/PhpStorm 2022.2 EAP.app.plugins/server-1.0-SNAPSHOT.jar, version=1.0-SNAPSHOT, package=null, isBundled=false), packagePrefix=null, instanceId=2, state=active)
	... 12 more
```

**Comment by serganch** [comment]
@haringsrob probably the zip you've got after the build doesn't contain the LSP4j library for some reason. Could you please list its content? I've checked the package that I've built locally and lsp4j is there.

**Comment by serganch** [comment]
@haringsrob Sorry, that was actually a stupid advice. LSP4j is definitely there because otherwise that point couldn't have been reached. I'll check it tomorrow. Thank you for reporting!

**Comment by haringsrob** [comment]
hey @serganch actually, this was my fault. I used the file in libs and not distributions 🤦.

Now it connects fine. However, I get the following based on the cursor below:

<img width="297" alt="Screenshot 2022-09-01 at 20 09 07" src="https://user-images.githubusercontent.com/866743/187983493-c56582c3-ed22-4941-82e0-86de2c490c4a.png">

```
java.util.concurrent.CompletionException: java.lang.RuntimeException: java.lang.AssertionError: Item not in lookup: item=IntellijIdeaRulezzz; lookup items=[user, user, this, this, _ENV, _ENV, _SERVER, _SERVER, _POST, _POST, argv, argv, argc, argc, HTTP_ENV_VARS, HTTP_ENV_VARS, HTTP_SESSION_VARS, HTTP_SESSION_VARS, _REQUEST, _REQUEST, HTTP_POST_FILES, HTTP_POST_FILES, GLOBALS, GLOBALS, http_response_header, http_response_header, _COOKIE, _COOKIE, php_errormsg, php_errormsg, HTTP_RAW_POST_DATA, HTTP_RAW_POST_DATA, HTTP_SERVER_VARS, HTTP_SERVER_VARS, _SESSION, _SESSION, _FILES, _FILES, HTTP_POST_VARS, HTTP_POST_VARS, HTTP_GET_VARS, HTTP_GET_VARS, _GET, _GET, IntellijIdeaRulezzz]
```

But, it runs from phpstorm headless mode just fine.

**Comment by haringsrob** [comment]
What works (as far as I could find):

- Find references
- Diagnostics
- code actions
- Formatting
- Goto definition
- Goto type definition

Does not work:
- Workspace/document symbols
- completion

This is really exciting! One thing is unfortunate that it (currently) only works over websocket I believe? I have not found a way yet to configure it with (neo)vim which is the dream team (usually over stdio).

Let me know if I can provide more info. Also, happy to sponsor this project as this is something on my wishlist for years.

**Comment by serganch** [comment]
@haringsrob thank you for feedback!

Currently the server works over TCP only. It's easy to make an option to run it over stdio, however. We haven't done it yet because we're not using it in production mode, while it's much easier to debug when it runs as a TCP server.

A couple of notes:

1. The plugin is intended to work in headless mode only. Parallel editing is a pain, LSP doesn't support it, so don't we. Currently you have to manually switch the headless mode on. We're planning to make it less cumbersome.
2. Currently workspace/document symbol search is implemented for java, python and kotlin. We're going to make a "default" implementation for any language with some limitations comparing to language specific ones, so PHP should be covered as well.

Also I didn't quite get it whether completion isn't working in GUI mode only (which is normal), or not working at all. Would be nice if you clarify that.

Thanks!

**Comment by haringsrob** [comment]
Hey!

I was running it in headless mode, the error I shared was from the console in vscode.

And yes i understand it is nor production ready but honestly this is really exciting for me :)

Cheers!

**Comment by serganch** [comment]
@haringsrob okay, #37 is created. Thank you for trying it out!

**Comment by serganch** [comment]
@haringsrob JFYI the project changed its name. Now it's IdeaLS. So did the repository.
