### ISSUE TITLE
Incorrect completion suggestions via multiple access operators

### ISSUE THREAD

**Issue by zishkaz** [serganch/intellij-lsp#24]
**Description**

Incorrect completion suggestions via multiple "." access operators.

**To reproduce**

Steps:

1. Run VsCode extension.
2. Write this code:

```java
public class Main {

    public static void main(String args[]) {
        System...
    }
}
```

**Expected behavior**

No completion suggestions are made.

**Actual behavior**

Every 3 sequantial access operators provide a completion suggest list.

**Visual proofs (screenshots, logs, images)**

![2022-08-15_18-23-34](https://user-images.githubusercontent.com/71882967/184665464-87ad46b9-da41-4209-93bd-5ea0f1e41cb3.png)

**Environment**

_OS_: Windows 10
_JDK_: Amazon Coretto 17.0.4
_Intellij IDEA_: Build #IU-222.3345.118
_VsCode_: version 1.70.1

**Comment by serganch** [comment]
This is how IDEA works. If you do the same thing in the IDEA you'll see similar results. We don't correct IDEA's behavior. Not at this stage at least.

**Comment by zishkaz** [comment]
As far as I am concerned IDEA does not do that. If you put multiple access operators consequently, IDEA won't suggest completions (I have just checked)

**Comment by serganch** [comment]
![screenshot](https://user-images.githubusercontent.com/6031865/184845073-4e3b9fd3-9798-4809-9f5c-4be600139547.png)

**Comment by zishkaz** [comment]
Perhaps we have IDEA version mismatch

![image](https://user-images.githubusercontent.com/71882967/184845461-ed37a1b5-9242-4380-aead-efc7d82dcc81.png)

**Comment by serganch** [comment]
Mine is 2022.2 and the same is used in the project

**Comment by serganch** [comment]
To check what the actually used IDEA really does or not launch it with `gradle plainIdea`

**Comment by zishkaz** [comment]
I have 2022.2 in plainIdea, perhaps this is jdk-related problem. Nevertheless, this does not seem like a big problem, so It think this issue can be closed
